dakota_technical_assessment:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: energy_analytics
      schema: analytics
      threads: 4